import { access, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const checks = [];
const check = (name, ok, detail) => checks.push({ name, ok: Boolean(ok), detail });
async function exists(file) { try { await access(path.join(root,file)); return true; } catch { return false; } }
check('production API entrypoint', await exists('apps/api/server.mjs'), 'HTTP entrypoint exists');
check('container definition', await exists('Dockerfile'), 'Production container exists');
check('production compose reference', await exists('infra/docker-compose.production.yml'), 'API/Postgres/Redis deployment reference exists');
check('V115 execution runtime services', await exists('apps/api/runtime-store.mjs') && await exists('apps/worker/runtime.mjs') && await exists('apps/worker/main.mjs') && await exists('infra/postgres/FINAL-MIGRATION-V115.sql') && await exists('infra/postgres/API-ROLE-GRANTS-V115.sql'), 'PostgreSQL queue/outbox/scheduler and restricted worker runtime source exists');
check('environment template', await exists('.env.example'), 'Required configuration is documented');
check('V114 tenant Growth Center and billing service', await exists('apps/api/growth-store.mjs') && await exists('apps/api/growth-routes.mjs') && await exists('apps/api/paddle-billing.mjs'), 'Authenticated CRM, builder and Paddle billing services exist');
const api = await readFile(path.join(root,'apps/api/server.mjs'),'utf8');
const dbConfig = await readFile(path.join(root,'apps/api/database-config.mjs'),'utf8');
check('secure HTTP defaults', api.includes('x-content-type-options') && api.includes('x-frame-options') && api.includes('cache-control'), 'Security response headers are set');
check('production configuration gate', api.includes('ATLAS_DATABASE_URL') && api.includes('ATLAS_SESSION_SECRET') && api.includes('ATLAS_ACTION_APPROVAL_KEY') && api.includes('ATLAS_PUBLIC_ORIGIN'), 'Production startup requires critical configuration');
check('production PostgreSQL TLS verification', api.includes('createPostgresPoolConfig(env') && dbConfig.includes("ssl = { rejectUnauthorized: true }") && dbConfig.includes("'sslmode', 'ssl', 'sslcert', 'sslkey', 'sslrootcert'") && dbConfig.includes('ATLAS_DATABASE_SSL_CA_FILE'), 'Production database connections verify TLS certificates and ignore weaker URL TLS overrides');
const authStore = await readFile(path.join(root,'apps/api/postgres-auth-store.mjs'),'utf8');
check('production PostgreSQL runtime-role verification', api.includes("runtime === 'production'") && api.includes('assertSafeRuntimeRole()') && authStore.includes("role.role_name !== 'atlas_app'"), 'Production refuses database connections with elevated or RLS-bypassing privileges');
const worker = await readFile(path.join(root,'apps/worker/main.mjs'),'utf8');
const runtimeSql = await readFile(path.join(root,'infra/postgres/FINAL-MIGRATION-V115.sql'),'utf8');
const runtimeGrants = await readFile(path.join(root,'infra/postgres/API-ROLE-GRANTS-V115.sql'),'utf8');
check('V115 queue RLS and distinct worker identity', runtimeSql.includes('FORCE ROW LEVEL SECURITY') && runtimeSql.includes('FOR UPDATE SKIP LOCKED') && runtimeGrants.includes('atlas_worker LOGIN NOSUPERUSER') && worker.includes('assertSafeWorkerRole()') && worker.includes('ATLAS_WORKER_DATABASE_URL'), 'Queue uses forced RLS and SKIP LOCKED, with a separately configured non-bypass worker role');
check('production mail and owner gates', api.includes('ATLAS_EMAIL_PROVIDER_TOKEN') && api.includes('ATLAS_EMAIL_FROM') && api.includes("env.ATLAS_EMAIL_PROVIDER !== 'postmark'") && api.includes('ATLAS_PLATFORM_OWNER_EMAIL'), 'Production requires a verified configured owner and transactional-email provider');
check('authenticated tenant API and connected readiness', api.includes('authenticatedApi: Boolean(authApi)') && api.includes('growthApi.handle(req, res)') && api.includes('authStore.ping()') && authStore.includes("to_regclass('public.atlas_runtime_jobs')"), 'Product routes enable only with PostgreSQL and readiness requires identity, Growth Center/billing and V115 execution schema');
const auth = await readFile(path.join(root,'apps/api/auth-routes.mjs'),'utf8');
check('trusted proxy client identity', api.includes("ATLAS_TRUST_PROXY !== 'true'") && auth.includes('isIP(candidate) !== 0') && auth.includes('trusted_client_ip_unavailable'), 'Production auth throttling requires a valid client IP from the trusted edge');
const migrationRunner = await readFile(path.join(root,'scripts/migrate.mjs'),'utf8');
const grants = await readFile(path.join(root,'infra/postgres/API-ROLE-GRANTS-V112.sql'),'utf8');
check('tenant authority from trusted session only', auth.includes('store.getSession({ sessionHash: hashOpaqueToken(raw) })') && auth.includes('ownerEmail: env.ATLAS_PLATFORM_OWNER_EMAIL') && !/body\.(?:platformOwner|globalRole|isPlatformOwner|ownerEmail)/.test(auth), 'Global authority comes from a trusted session and configured owner identity; request flags do not confer it');
const identitySql = await readFile(path.join(root,'infra/postgres/FINAL-MIGRATION-V112.sql'),'utf8');
check('forced RLS identity schema', identitySql.includes('atlas_organization_memberships') && identitySql.includes('atlas_auth_sessions') && identitySql.includes('atlas_auth_tokens') && identitySql.includes('FORCE ROW LEVEL SECURITY') && !/platform_owner/i.test(identitySql), 'Identity and tenant tables enforce RLS without a customer platform-owner role');
check('runtime/migration role split', grants.includes('atlas_app') && migrationRunner.includes('ATLAS_MIGRATION_DATABASE_URL') && migrationRunner.includes('ATLAS_ALLOW_SHARED_MIGRATION_ROLE'), 'Database grants separate restricted runtime API privileges from schema migration authority');
const growthRoutes = await readFile(path.join(root,'apps/api/growth-routes.mjs'),'utf8');
const growthStore = await readFile(path.join(root,'apps/api/growth-store.mjs'),'utf8');
const growthSql = await readFile(path.join(root,'infra/postgres/FINAL-MIGRATION-V114.sql'),'utf8');
const growthGrants = await readFile(path.join(root,'infra/postgres/API-ROLE-GRANTS-V114.sql'),'utf8');
check('single platform-owner identity remains separate', growthRoutes.includes('resolveAtlasAuthority') && growthStore.includes('atlas_organization_memberships') && growthStore.includes('organization_not_found') && !/platformOwner|globalRole/.test(growthStore), 'Even a platform-owner session must have a fresh tenant membership to read or mutate customer Growth Center data');
check('V114 forced tenant RLS and restricted grants', growthSql.includes('atlas_growth_items') && growthSql.includes('atlas_paddle_subscriptions') && growthSql.includes('FORCE ROW LEVEL SECURITY') && growthGrants.includes('rolbypassrls') && growthGrants.includes('pg_auth_members'), 'Growth and Paddle tables use forced RLS with a checked non-bypass/non-inheriting application role');
const paddle = await readFile(path.join(root,'apps/api/paddle-billing.mjs'),'utf8');
check('Paddle webhook signature and checkout boundaries', paddle.includes('timingSafeEqual') && paddle.includes('toleranceSeconds = 5') && paddle.includes('rawBody') && paddle.includes('parsed.origin'), 'Billing checks raw-body signatures, freshness and exact Paddle checkout origins');
const billingRoutes = await readFile(path.join(root,'apps/api/growth-routes.mjs'),'utf8');
const billingStore = await readFile(path.join(root,'apps/api/growth-store.mjs'),'utf8');
const billingUi = await readFile(path.join(root,'apps/command-center/auth.html'),'utf8');
check('14-day trial price gate and repeat-use marker', paddle.includes('ATLAS_FREE_TRIAL_DAYS = 14') && paddle.includes('verifyPaddleFreeTrialPrice') && paddle.includes('unit_price_overrides') && billingRoutes.includes('trialStartedAt') && billingStore.includes('trial_started_at'), 'Trial checkout requires a provider-verified free recurring price and a tenant-sticky marker prevents another trial');
check('authenticated cancellation portal and user disclosure', paddle.includes('createPaddlePortalSession') && billingRoutes.includes("path === '/api/v1/billing/portal'") && billingUi.includes('Start 14-day free trial') && billingUi.includes('Manage or cancel plan'), 'Only tenant billing managers receive validated Paddle portal links, and the workspace explains trial and cancellation controls');
check('Paddle configuration documented', await readFile(path.join(root,'.env.example'),'utf8').then(text => text.includes('ATLAS_PADDLE_WEBHOOK_SECRET') && text.includes('ATLAS_PADDLE_PRICE_STARTER')), 'Paddle API, webhook and plan-price keys have deployment configuration entries');
check('production-safe public-origin requirement', api.includes('/example\\.com$/i') && api.includes('ATLAS_PUBLIC_ORIGIN must be the real HTTPS Atlas origin'), 'Production blocks the sample origin and requires the future real HTTPS domain');
const compose = await readFile(path.join(root,'infra/docker-compose.production.yml'),'utf8');
check('production Compose secrets and loopback bind', compose.includes('ATLAS_POSTGRES_SUPERUSER_PASSWORD:?') && !compose.includes('change-me-before-use') && compose.includes('127.0.0.1:8080:8080'), 'Database bootstrap password is required from deployment configuration and the API port is restricted to the local HTTPS proxy');
const workerCompose = compose.split(/\r?\n  worker:\r?\n/)[1] || '';
check('optional worker profile requires external handlers', compose.includes('profiles: ["workers"]') && workerCompose.includes('ATLAS_WORKER_HANDLERS_PATH:?') && workerCompose.includes('/app/apps/worker/handlers/production.mjs:ro') && !workerCompose.includes('env_file:'), 'Worker deployment stays opt-in until reviewed handlers are mounted and receives no shared API environment file');
const readme = await readFile(path.join(root,'README.md'),'utf8');
check('production boundary retained', readme.includes('Local JSON/state remains development-only') && readme.includes('millions-of-users capacity claim is verified') && readme.includes('TOTP/2FA') && readme.includes('remain future work'), 'Implemented foundations, local-state boundary and unverified scale are explicit');
for (const r of checks) process.stdout.write((r.ok ? 'PASS ' : 'FAIL ') + r.name + ': ' + r.detail + '\n');
const failed = checks.filter(r => !r.ok).length;
process.stdout.write('Atlas production check: ' + (checks.length-failed) + '/' + checks.length + ' checks passed.\n');
if (failed) process.exitCode = 1;
