import { access, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const checks = [];
const check = (name, ok, detail) => checks.push({ name, ok: Boolean(ok), detail });
async function exists(file) { try { await access(path.join(root,file)); return true; } catch { return false; } }
check('production API entrypoint', await exists('apps/api/server.mjs'), 'HTTP entrypoint exists');
check('container definition', await exists('Dockerfile'), 'Production container exists');
check('production compose reference', await exists('infra/docker-compose.production.yml'), 'API/Postgres/Redis deployment reference exists');
check('environment template', await exists('.env.example'), 'Required configuration is documented');
check('V114 tenant Growth Center and billing service', await exists('apps/api/growth-store.mjs') && await exists('apps/api/growth-routes.mjs') && await exists('apps/api/paddle-billing.mjs'), 'Authenticated CRM, builder and Paddle billing services exist');
const api = await readFile(path.join(root,'apps/api/server.mjs'),'utf8');
const dbConfig = await readFile(path.join(root,'apps/api/database-config.mjs'),'utf8');
check('secure HTTP defaults', api.includes('x-content-type-options') && api.includes('x-frame-options') && api.includes('cache-control'), 'Security response headers are set');
check('production configuration gate', api.includes('ATLAS_DATABASE_URL') && api.includes('ATLAS_SESSION_SECRET') && api.includes('ATLAS_ACTION_APPROVAL_KEY') && api.includes('ATLAS_PUBLIC_ORIGIN'), 'Production startup requires critical configuration');
check('production PostgreSQL TLS verification', api.includes('createPostgresPoolConfig(env') && dbConfig.includes("ssl = { rejectUnauthorized: true }") && dbConfig.includes("'sslmode', 'ssl', 'sslcert', 'sslkey', 'sslrootcert'") && dbConfig.includes('ATLAS_DATABASE_SSL_CA_FILE'), 'Production database connections verify TLS certificates and ignore weaker URL TLS overrides');
check('production mail and owner gates', api.includes('ATLAS_EMAIL_PROVIDER_TOKEN') && api.includes('ATLAS_EMAIL_FROM') && api.includes("env.ATLAS_EMAIL_PROVIDER !== 'postmark'") && api.includes('ATLAS_PLATFORM_OWNER_EMAIL'), 'Production requires a verified configured owner and transactional-email provider');
check('authenticated tenant API and connected readiness', api.includes('authenticatedApi: Boolean(authApi)') && api.includes('growthApi.handle(req, res)') && api.includes('authStore.ping()'), 'Product routes enable only with PostgreSQL and readiness requires identity plus Growth Center/billing tables');
const auth = await readFile(path.join(root,'apps/api/auth-routes.mjs'),'utf8');
check('trusted proxy client identity', api.includes("ATLAS_TRUST_PROXY !== 'true'") && auth.includes('isIP(candidate) !== 0') && auth.includes('trusted_client_ip_unavailable'), 'Production auth throttling requires a valid client IP from the trusted edge');
const migrationRunner = await readFile(path.join(root,'scripts/migrate.mjs'),'utf8');
const grants = await readFile(path.join(root,'infra/postgres/API-ROLE-GRANTS-V112.sql'),'utf8');
check('tenant authority from trusted session only', auth.includes('store.getSession({ sessionHash: hashOpaqueToken(raw) })') && auth.includes('ownerEmail: env.ATLAS_PLATFORM_OWNER_EMAIL') && !/body\.(?:platformOwner|globalRole|isPlatformOwner|ownerEmail)/.test(auth), 'Global authority comes from a trusted session and configured owner identity; request flags do not confer it');
const identitySql = await readFile(path.join(root,'infra/postgres/FINAL-MIGRATION-V112.sql'),'utf8');
check('forced RLS identity schema', identitySql.includes('atlas_organization_memberships') && identitySql.includes('atlas_auth_sessions') && identitySql.includes('atlas_auth_tokens') && identitySql.includes('FORCE ROW LEVEL SECURITY') && !/platform_owner/i.test(identitySql), 'Identity and tenant tables enforce RLS without a customer platform-owner role');
check('runtime/migration role split', grants.includes('atlas_app') && migrationRunner.includes('ATLAS_MIGRATION_DATABASE_URL') && migrationRunner.includes('ATLAS_ALLOW_SHARED_MIGRATION_ROLE'), 'Database grants separate restricted runtime API privileges from schema migration authority');
const growthRoutes = await readFile(path.join(root,'apps/api/growth-routes.mjs'),'utf8');
const growthStore = await readFile(path.join(root,'apps/api/growth-store.mjs'),'utf8');
const growthSql = await readFile(path.join(root,'infra/postgres/FINAL-MIGRATION-V114.sql'),'utf8');
const growthGrants = await readFile(path.join(root,'infra/postgres/API-ROLE-GRANTS-V114.sql'),'utf8');
check('single platform-owner identity remains separate', growthRoutes.includes('resolveAtlasAuthority') && growthStore.includes('atlas_organization_memberships') && growthStore.includes('organization_not_found') && !/platformOwner|globalRole/.test(growthStore), 'Even a platform-owner session must have a fresh tenant membership to read or mutate customer Growth Center data');
check('V114 forced tenant RLS and restricted grants', growthSql.includes('atlas_growth_items') && growthSql.includes('atlas_paddle_subscriptions') && growthSql.includes('FORCE ROW LEVEL SECURITY') && growthGrants.includes('rolbypassrls') && growthGrants.includes('pg_auth_members'), 'Growth and Paddle tables use forced RLS with a checked non-bypass/non-inheriting application role');
const paddle = await readFile(path.join(root,'apps/api/paddle-billing.mjs'),'utf8');
check('Paddle webhook signature and checkout boundaries', paddle.includes('timingSafeEqual') && paddle.includes('toleranceSeconds = 5') && paddle.includes('rawBody') && paddle.includes('parsed.origin'), 'Billing checks raw-body signatures, freshness and exact Paddle checkout origins');
check('Paddle configuration documented', await readFile(path.join(root,'.env.example'),'utf8').then(text => text.includes('ATLAS_PADDLE_WEBHOOK_SECRET') && text.includes('ATLAS_PADDLE_PRICE_STARTER')), 'Paddle API, webhook and plan-price keys have deployment configuration entries');
check('production-safe public-origin requirement', api.includes('/example\\.com$/i') && api.includes('ATLAS_PUBLIC_ORIGIN must be the real HTTPS Atlas origin'), 'Production blocks the sample origin and requires the future real HTTPS domain');
const readme = await readFile(path.join(root,'README.md'),'utf8');
check('production boundary retained', readme.includes('Local JSON/state remains development-only') && readme.includes('millions-of-users capacity claim is verified') && readme.includes('TOTP/2FA') && readme.includes('remain future work'), 'Implemented foundations, local-state boundary and unverified scale are explicit');
for (const r of checks) process.stdout.write((r.ok ? 'PASS ' : 'FAIL ') + r.name + ': ' + r.detail + '\n');
const failed = checks.filter(r => !r.ok).length;
process.stdout.write('Atlas production check: ' + (checks.length-failed) + '/' + checks.length + ' checks passed.\n');
if (failed) process.exitCode = 1;
