const state={connectors:[{name:'CRM',state:'healthy'},{name:'Accounting',state:'degraded'},{name:'Messaging',state:'healthy'}],evaluation:{score:97},operations:{pipeline:284500,weighted:219300,pendingApprovals:7,running:3,failed:1},sync:{lag:42,webhooks:128,deadLetters:2},graph:{customers:1840,relationships:6230,atRisk:37},revenue:{won:84200,expansion:14,closePlans:6},risks:[{type:'stale_deals',severity:'high',count:6},{type:'overdue_tasks',severity:'medium',count:14},{type:'failed_workflows',severity:'high',count:1}],actions:[{id:'a-102',title:'Refresh six stale deals',status:'pending_approval'},{id:'a-103',title:'Retry failed workflow',status:'pending_approval'},{id:'a-104',title:'Review overdue task queue',status:'pending_approval'}]};
const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function render(){document.querySelector('#app').innerHTML='<main class="shell"><header class="top"><div><div class="brand">Atlas Command Center</div><div class="sub">Revenue, customer intelligence, durable operations and AI workforce in one laptop-first view.</div></div><button class="btn" id="refresh">Refresh pulse</button></header><section class="grid">'+
'<div class="card"><div class="label">Pipeline</div><div class="kpi">'+money(state.operations.pipeline)+'</div><div class="sub">weighted '+money(state.operations.weighted)+'</div></div>'+
'<div class="card"><div class="label">Connector health</div><div class="kpi">'+state.connectors.filter(x=>x.state==='healthy').length+'/'+state.connectors.length+'</div><div class="sub">healthy providers</div></div>'+
'<div class="card"><div class="label">Agent evaluation</div><div class="kpi">'+state.evaluation.score+'%</div><div class="bar"><div class="fill" style="width:'+state.evaluation.score+'%"></div></div></div>'+
'<div class="card"><div class="label">Approval queue</div><div class="kpi">'+state.operations.pendingApprovals+'</div><div class="sub">human decisions required</div></div>'+
'<div class="card wide"><div class="label">Sync fabric</div><div class="risk"><span>sync lag</span><span class="pill medium">'+state.sync.lag+'s</span></div><div class="risk"><span>webhooks accepted</span><span class="pill ok">'+state.sync.webhooks+'</span></div><div class="risk"><span>dead-letter jobs</span><span class="pill high">'+state.sync.deadLetters+'</span></div></div>'+
'<div class="card wide"><div class="label">Customer intelligence graph</div><div class="risk"><span>customers</span><strong>'+state.graph.customers+'</strong></div><div class="risk"><span>relationships</span><strong>'+state.graph.relationships+'</strong></div><div class="risk"><span>at-risk accounts</span><span class="pill high">'+state.graph.atRisk+'</span></div></div>'+
'<div class="card wide"><div class="label">Revenue cockpit</div><div class="risk"><span>won</span><strong>'+money(state.revenue.won)+'</strong></div><div class="risk"><span>expansion candidates</span><strong>'+state.revenue.expansion+'</strong></div><div class="risk"><span>close plans</span><strong>'+state.revenue.closePlans+'</strong></div></div>'+
'<div class="card wide"><div class="label">Operational risks</div>'+state.risks.map(r=>'<div class="risk"><span>'+r.type.replaceAll('_',' ')+'</span><span class="pill '+r.severity+'">'+r.count+' · '+r.severity+'</span></div>').join('')+'</div>'+
'<div class="card wide actions"><div class="label">Action inbox</div>'+state.actions.map(a=>'<div class="action"><div><strong>'+a.title+'</strong><div class="sub">'+a.status+'</div></div><button class="btn approve" data-id="'+a.id+'">Approve</button></div>').join('')+'</div>'+
'<div class="card wide"><div class="label">AI workforce</div><p>Evaluation, permissions and approvals remain server-side controls. Queue workers own execution leases; the dashboard is not the source of truth.</p><div class="sub">Atlas V90 · laptop-first Business OS</div></div></section></main>';document.querySelector('#refresh').onclick=()=>{state.operations.running+=1;render()};document.querySelectorAll('.approve').forEach(b=>b.onclick=()=>{const a=state.actions.find(x=>x.id===b.dataset.id);a.status='approved';state.operations.pendingApprovals=Math.max(0,state.operations.pendingApprovals-1);render()})}render();
