const $=s=>document.querySelector(s);
let csrf='';
async function me(){const r=await fetch('/api/v1/me',{credentials:'same-origin'});if(!r.ok)throw new Error('Authentication required');const x=await r.json();csrf=x.csrfToken||''}
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(csrf)headers['x-atlas-csrf']=csrf;const r=await fetch(path,{credentials:'same-origin',...options,headers});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.message||x.error||'Request failed');return x}
function note(t){const n=$('#notice');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),3000)}
function render(item){$('#state').textContent=item?.status||'Not configured';$('#state').className='pill '+(item?.status==='active'?'good':'');$('#displayName').value=item?.display_name||'Atlas Copilot';$('#origins').value=(item?.allowed_origins||[]).join('\n');$('#release').value=item?.release_snapshot?JSON.stringify(item.release_snapshot,null,2):'';$('#embed').textContent=item?.widget_key?'<script src="'+location.origin+'/copilot-widget.mjs" data-atlas-widget-key="'+item.widget_key+'"></script>':'Save a live release to generate the embed.'}
async function config(){render((await api('/api/v1/platform/copilot/config')).item)}
async function handoffs(){const x=await api('/api/v1/platform/copilot/handoffs');const el=$('#handoffs');el.innerHTML=x.items.length?x.items.map(i=>'<div class="item"><strong>'+i.reason.replaceAll('_',' ')+'</strong><span>'+i.session_id+' · '+i.status+'</span>'+(i.status==='pending'?'<div class="buttons"><button data-h="'+i.handoff_id+'" data-s="accepted">Accept</button><button data-h="'+i.handoff_id+'" data-s="resolved">Resolve</button><button data-h="'+i.handoff_id+'" data-s="canceled">Cancel</button></div>':'')+'</div>').join(''):'<div class="empty">No handoffs.</div>'}
async function approvals(){const x=await api('/api/v1/platform/copilot/approvals');const el=$('#approvals');el.innerHTML=x.items.length?x.items.map(i=>'<div class="item"><strong>'+i.action_key+'</strong><span>'+i.session_id+' · '+new Date(i.requested_at).toLocaleString()+'</span><div class="buttons"><button data-a="'+i.approval_id+'" data-s="approved">Approve</button><button data-a="'+i.approval_id+'" data-s="denied">Deny</button></div></div>').join(''):'<div class="empty">No pending approvals.</div>'}
async function refresh(){await config();await Promise.all([handoffs(),approvals()])}
$('#config-form').addEventListener('submit',async e=>{e.preventDefault();try{const release=JSON.parse($('#release').value);const x=await api('/api/v1/platform/copilot/config',{method:'PUT',body:JSON.stringify({configId:null,widgetKey:null,displayName:$('#displayName').value,allowedOrigins:$('#origins').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),releaseSnapshot:release})});render(x.item);note('Copilot activated.')}catch(err){note(err.message)}});
$('#refresh').onclick=()=>refresh().catch(e=>note(e.message));$('#handoff-refresh').onclick=()=>handoffs().catch(e=>note(e.message));$('#approval-refresh').onclick=()=>approvals().catch(e=>note(e.message));
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#embed').textContent);note('Embed copied.')}catch{note('Copy unavailable in this browser.')}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.h)await api('/api/v1/platform/copilot/handoffs/'+b.dataset.h,{method:'POST',body:JSON.stringify({status:b.dataset.s})});if(b.dataset.a)await api('/api/v1/platform/copilot/approvals/'+b.dataset.a,{method:'POST',body:JSON.stringify({status:b.dataset.s})});if(b.dataset.h||b.dataset.a){await Promise.all([handoffs(),approvals()]);note('Updated.')}}catch(err){note(err.message)}});
me().then(refresh).catch(e=>{note(e.message);setTimeout(()=>location.href='/login',500)});