import {createAuthError} from './auth-contracts.mjs';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export class PostgresCapabilityStore{
 constructor(pool){this.pool=pool;}
 async #tx({actorId,tenantId,write=false},work){if(!UUID.test(actorId||'')||!UUID.test(tenantId||''))throw createAuthError(409,'workspace_required');const c=await this.pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor_id',$1,true)",[actorId]);const m=await c.query("SELECT role_key FROM atlas_organization_memberships WHERE tenant_id=$1 AND user_id=$2 AND status='active'",[tenantId,actorId]);if(!m.rowCount)throw createAuthError(404,'organization_not_found');await c.query("SELECT set_config('app.tenant_id',$1,true)",[tenantId]);if(write&&!['owner','admin'].includes(m.rows[0].role_key))throw createAuthError(403,'capability_write_forbidden');const r=await work(c);await c.query('COMMIT');return r;}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release();}}
 async listConnections(who){return this.#tx(who,c=>c.query('SELECT connection_id,provider_key,channel,status,scopes,metadata,last_verified_at,version,created_at,updated_at FROM atlas_v122_provider_connections WHERE tenant_id=$1 ORDER BY updated_at DESC',[who.tenantId]).then(r=>r.rows));}
 async createConnection(who,input){return this.#tx({...who,write:true},async c=>{const r=await c.query("INSERT INTO atlas_v122_provider_connections(tenant_id,provider_key,channel,status,credential_ref,scopes,metadata) VALUES($1,$2,$3,'draft',$4,$5::jsonb,$6::jsonb) RETURNING connection_id,provider_key,channel,status,credential_ref,scopes,metadata,version,created_at,updated_at",[who.tenantId,input.providerKey,input.channel||null,input.credentialRef||null,JSON.stringify(input.scopes||[]),JSON.stringify(input.metadata||{})]);return r.rows[0];});}
 async listConversations(who,{status=null,channel=null,limit=50}={}){const safe=Math.min(100,Math.max(1,Number(limit)||50));return this.#tx(who,c=>c.query("SELECT conversation_id,contact_id,channel,provider_connection_id,external_thread_ref,status,assigned_agent_id,handoff_reason,subject,last_message_at,version,created_at,updated_at FROM atlas_v122_conversations WHERE tenant_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR channel=$3) ORDER BY COALESCE(last_message_at,created_at) DESC LIMIT $4",[who.tenantId,status,channel,safe]).then(r=>r.rows));}
 async createConversation(who,input){return this.#tx({...who,write:true},async c=>{const r=await c.query("INSERT INTO atlas_v122_conversations(tenant_id,contact_id,channel,provider_connection_id,external_thread_ref,subject) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,channel,external_thread_ref) DO UPDATE SET updated_at=now() RETURNING *",[who.tenantId,input.contactId||null,input.channel,input.providerConnectionId||null,input.externalThreadRef,input.subject||null]);return r.rows[0];});}
 async handoff(who,id,input){return this.#tx({...who,write:true},async c=>{const r=await c.query("UPDATE atlas_v122_conversations SET assigned_agent_id=$4,handoff_reason=$5,version=version+1,updated_at=now() WHERE tenant_id=$1 AND conversation_id=$2 AND version=$3 RETURNING *",[who.tenantId,id,input.expectedVersion,input.agentId,input.reason]);if(!r.rowCount)throw createAuthError(409,'conversation_version_conflict');return r.rows[0];});}
 async listDefinitions(who,kind,marketing=false){return this.#tx(who,c=>c.query(marketing?"SELECT definition_id,kind,key,status,config,version,created_at,updated_at FROM atlas_v122_marketing_definitions WHERE tenant_id=$1 AND ($2::text IS NULL OR kind=$2) ORDER BY updated_at DESC":"SELECT definition_id,kind,key,label,schema,version,created_at,updated_at FROM atlas_v122_crm_definitions WHERE tenant_id=$1 AND ($2::text IS NULL OR kind=$2) ORDER BY updated_at DESC",[who.tenantId,kind||null]).then(r=>r.rows));}
 async createDefinition(who,input,marketing=false){return this.#tx({...who,write:true},c=>c.query(marketing?"INSERT INTO atlas_v122_marketing_definitions(tenant_id,kind,key,status,config) VALUES($1,$2,$3,$4,$5::jsonb) RETURNING *":"INSERT INTO atlas_v122_crm_definitions(tenant_id,kind,key,label,schema) VALUES($1,$2,$3,$4,$5::jsonb) RETURNING *",[who.tenantId,input.kind,input.key,input.status||'draft',JSON.stringify(input.config||input.schema||{}),input.label||input.key]).then(r=>r.rows[0]));}
 async enterprise(who){return this.#tx(who,c=>c.query('SELECT * FROM atlas_v122_enterprise_controls WHERE tenant_id=$1',[who.tenantId]).then(async r=>r.rows[0]||{tenant_id:who.tenantId,mfa_required:false,sso_required:false,scim_enabled:false,waf_required:true,rotation_days:90,audit_retention_days:365,dr_rpo_seconds:900,dr_rto_seconds:3600,load_test_status:'not_run'}));}
 async updateEnterprise(who,input){return this.#tx({...who,write:true},c=>c.query("INSERT INTO atlas_v122_enterprise_controls(tenant_id,mfa_required,sso_required,scim_enabled,waf_required,kms_key_ref,rotation_days,audit_retention_days,dr_rpo_seconds,dr_rto_seconds,load_test_status,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,now()) ON CONFLICT(tenant_id) DO UPDATE SET mfa_required=EXCLUDED.mfa_required,sso_required=EXCLUDED.sso_required,scim_enabled=EXCLUDED.scim_enabled,waf_required=EXCLUDED.waf_required,kms_key_ref=EXCLUDED.kms_key_ref,rotation_days=EXCLUDED.rotation_days,audit_retention_days=EXCLUDED.audit_retention_days,dr_rpo_seconds=EXCLUDED.dr_rpo_seconds,dr_rto_seconds=EXCLUDED.dr_rto_seconds,load_test_status=EXCLUDED.load_test_status,updated_at=now() RETURNING *",[who.tenantId,!!input.mfaRequired,!!input.ssoRequired,!!input.scimEnabled, input.wafRequired!==false,input.kmsKeyRef||null,input.rotationDays||90,input.auditRetentionDays||365,input.drRpoSeconds||900,input.drRtoSeconds||3600,input.loadTestStatus||'not_run']).then(r=>r.rows[0]));}
}
