import {createHash,randomUUID} from 'node:crypto';
import {createAuthError,parseCookies,sessionCookieName,hashOpaqueToken,verifyCsrf} from './auth-contracts.mjs';
import {securityHeaders} from './security.mjs';
import {capabilityMatrix} from '../../packages/atlas-core/capability-fabric.mjs';
import {buildOutboundIdempotencyKey} from '../../packages/atlas-core/unified-inbox.mjs';
import {parseAndVerifyInboxWebhook} from './inbox-webhooks.mjs';
function send(res,status,body,env){res.writeHead(status,{...securityHeaders(env),'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body));return true;}
async function body(req,max=100000){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max)throw createAuthError(413,'request_too_large');chunks.push(c)}return Buffer.concat(chunks);}
async function json(req){try{return JSON.parse((await body(req)).toString('utf8'))}catch{throw createAuthError(400,'invalid_json')}}
function tokenHash(token){return createHash('sha256').update(token).digest('hex');}
export function createCapabilityApi({store,authStore,env=process.env,inboxContentStore=null,webhookSecretResolver=null}={}){
 async function who(req){const raw=parseCookies(req.headers.cookie).get(sessionCookieName(env));if(!raw)throw createAuthError(401,'authentication_required');const s=await authStore.getSession({sessionHash:hashOpaqueToken(raw)});if(!s?.tenantId)throw createAuthError(409,'workspace_required');return {actorId:s.user.id,tenantId:s.tenantId,session:s};}
 async function mutation(req,s){if(req.headers.origin&&req.headers.origin!==env.ATLAS_PUBLIC_ORIGIN)throw createAuthError(403,'origin_forbidden');if(!verifyCsrf(req.headers['x-atlas-csrf'],s.csrfToken))throw createAuthError(403,'csrf_failed');}
 async function webhook(req,res,url){const match=url.pathname.match(/^\/api\/v1\/inbox\/webhooks\/([A-Za-z0-9_-]{16,200})$/);if(!match)return false;if(req.method!=='POST')return send(res,405,{error:'method_not_allowed' },env);if(!webhookSecretResolver||!inboxContentStore)throw Object.assign(new Error('Inbox webhook services are not configured.'),{code:'inbox_webhook_unavailable'});const token=match[1],endpoint=await store.resolveWebhookEndpoint(tokenHash(token));if(!endpoint)throw createAuthError(404,'webhook_not_found');const raw=(await body(req,1000000)).toString('utf8');const headers=Object.fromEntries(Object.entries(req.headers).map(([k,v])=>[k.toLowerCase(),Array.isArray(v)?v.join(','):String(v||'')]));const secret=await webhookSecretResolver({tenantId:endpoint.tenant_id,endpointId:endpoint.endpoint_id,providerKey:endpoint.provider_key,secretRef:endpoint.signing_secret_ref});const publicUrl=new URL(env.ATLAS_PUBLIC_ORIGIN);publicUrl.pathname=url.pathname;publicUrl.search=url.search;const parsed=await parseAndVerifyInboxWebhook({providerKey:endpoint.provider_key,endpoint,secret,rawBody:raw,headers,url:publicUrl.toString(),query:Object.fromEntries(url.searchParams)});if(Array.isArray(endpoint.accepted_events)&&endpoint.accepted_events.length&&!endpoint.accepted_events.includes(parsed.eventType))return send(res,200,{status:'ignored'},env);if(parsed.kind==='receipt'){const applied=await store.applyReceipt(endpoint,parsed);return send(res,200,{status:applied?'processed':'ignored'},env);}if(parsed.kind==='ignored')return send(res,200,{status:'ignored'},env);const contentRef=await inboxContentStore.putMessageContent({tenantId:endpoint.tenant_id,messageId:parsed.eventRef,channel:parsed.channel,text:parsed.content?.text||'',html:parsed.content?.html||null,attachments:parsed.content?.attachments||[],metadata:{provider:endpoint.provider_key}});const result=await store.ingestInbound(endpoint,{...parsed,contentRef});return send(res,200,result,env);}
 return {async handle(req,res){const url=new URL(req.url||'/','http://localhost');try{if(url.pathname.startsWith('/api/v1/inbox/webhooks/'))return await webhook(req,res,url);if(!url.pathname.startsWith('/api/v1/platform/'))return false;const w=await who(req);
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/capabilities')return send(res,200,{items:capabilityMatrix()},env);
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/integrations')return send(res,200,{items:await store.listConnections(w)},env);
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/inbox/webhooks')return send(res,200,{items:await store.listWebhookEndpoints(w)},env);
 if(req.method==='POST'&&url.pathname==='/api/v1/platform/inbox/webhooks'){await mutation(req,w.session);const b=await json(req);return send(res,201,{item:await store.createWebhookEndpoint(w,b)},env);}
 if(req.method==='POST'&&url.pathname==='/api/v1/platform/integrations'){await mutation(req,w.session);return send(res,201,{item:await store.createConnection(w,await json(req))},env);}
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/inbox/conversations')return send(res,200,{items:await store.listConversations(w,{status:url.searchParams.get('status'),channel:url.searchParams.get('channel'),assignedAgentId:url.searchParams.get('assignedAgentId'),unreadOnly:url.searchParams.get('unreadOnly')==='true',limit:url.searchParams.get('limit')})},env);
 const conv=url.pathname.match(/^\/api\/v1\/platform\/inbox\/conversations\/([0-9a-f-]+)$/i);
 if(conv&&req.method==='GET')return send(res,200,{item:(await store.listConversations(w,{limit:100})).find(x=>x.conversation_id.toLowerCase()===conv[1].toLowerCase())||null},env);
 if(conv&&req.method==='POST'){await mutation(req,w.session);const b=await json(req);if(!inboxContentStore)throw Object.assign(new Error('Inbox content service is unavailable.'),{code:'inbox_content_store_unavailable'});const messageKey=randomUUID();const contentRef=await inboxContentStore.putMessageContent({tenantId:w.tenantId,messageId:messageKey,channel:b.channel,text:b.content?.text||'',html:b.content?.html||null,attachments:b.content?.attachments||[],metadata:{actorId:w.actorId}});const jobId=randomUUID();const idem=buildOutboundIdempotencyKey({tenantId:w.tenantId,conversationId:conv[1],channel:b.channel,clientKey:b.clientKey||messageKey});const item=await store.queueOutbound(w,{...b,conversationId:conv[1],contentRef,jobId,idempotencyKey:idem});return send(res,item.created?202:200,{item,jobId},env);}
 const msgs=url.pathname.match(/^\/api\/v1\/platform\/inbox\/conversations\/([0-9a-f-]+)\/messages$/i);
 if(msgs&&req.method==='GET')return send(res,200,{items:await store.listMessages(w,msgs[1],{limit:url.searchParams.get('limit'),before:url.searchParams.get('before')})},env);
 const read=url.pathname.match(/^\/api\/v1\/platform\/inbox\/conversations\/([0-9a-f-]+)\/read$/i);
 if(read&&req.method==='POST'){await mutation(req,w.session);const b=await json(req);return send(res,200,{item:await store.markRead(w,read[1],b.expectedVersion)},env);}
 const hand=url.pathname.match(/^\/api\/v1\/platform\/inbox\/conversations\/([0-9a-f-]+)\/handoff$/i);
 if(hand&&req.method==='POST'){await mutation(req,w.session);return send(res,200,{item:await store.handoff(w,hand[1],await json(req))},env);}
 if(req.method==='POST'&&url.pathname==='/api/v1/platform/inbox/conversations'){await mutation(req,w.session);return send(res,201,{item:await store.createConversation(w,await json(req))},env);}
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/crm/definitions')return send(res,200,{items:await store.listDefinitions(w,url.searchParams.get('kind'))},env);
 if(req.method==='POST'&&url.pathname==='/api/v1/platform/crm/definitions'){await mutation(req,w.session);return send(res,201,{item:await store.createDefinition(w,await json(req),false)},env);}
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/marketing/definitions')return send(res,200,{items:await store.listDefinitions(w,url.searchParams.get('kind'),true)},env);
 if(req.method==='POST'&&url.pathname==='/api/v1/platform/marketing/definitions'){await mutation(req,w.session);return send(res,201,{item:await store.createDefinition(w,await json(req),true)},env);}
 const svc=url.pathname.match(/^\/api\/v1\/platform\/service\/(requests|jobs|visits|quotes|invoices)$/);if(svc&&req.method==='GET')return send(res,200,{items:await store.serviceList(w,svc[1])},env);if(svc&&req.method==='POST'){await mutation(req,w.session);return send(res,201,{item:await store.serviceCreate(w,svc[1],await json(req))},env);}
 if(req.method==='GET'&&url.pathname==='/api/v1/platform/enterprise/controls')return send(res,200,{item:await store.enterprise(w)},env);
 if(req.method==='PATCH'&&url.pathname==='/api/v1/platform/enterprise/controls'){await mutation(req,w.session);return send(res,200,{item:await store.updateEnterprise(w,await json(req))},env);}
 return send(res,404,{error:'not_found'},env);}catch(e){return send(res,e.status||500,{error:e.code||'internal_error',message:e.status?e.message:undefined},env);}}};
}
